title: "svetixoxo"
description: "Mein Homelab-Abenteuer: Cloud, Smart Home & Self-Hosting"
author: "Svetlana"
url: "https://svetixoxo.github.io"
baseurl: ""

# Markdown-Einstellungen
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:title/
timezone: Europe/Berlin

# Theme
theme: null

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - pages/themen.md
  - pages/archiv.md

# Ausschl√ºsse
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
